### ISSUE TITLE
Feedback on enabling auto-complete in Slash Commands?

### ISSUE THREAD

**Issue by it33** [bitbackofen/slash-server-for-mattermost#1]
Thanks for sharing this back with the community! It's one of the first slash integrations in the world. 

When you feel it's ready to share, please let us know, we'd love to promote it!

Also, we have [a pull request on `master` for enabling auto-complete for slash commands.](https://github.com/mattermost/platform/pull/2169) 

I wondered if we could get your feedback? 

Would this be something you'd like to use? 

Would you have any feedback on the approach or documentation? 

We're hoping to improve Mattermost with each monthly release, and your feedback could help a lot!

**Comment by elpatron68** [comment]
Hi @it33 
I finally found some minutes to think about @kernicPanel s approach. I think it has lots of potential, but loads configuration from Mattermost to the server side. I'm not sure if it's really easier to deal with autocompletion on the server side, but for sure, it could be more powerful.

I will try to write some docs around my approach next weekend. For the goals of our team, this solution is okay as we will never have dozens of compilacted commands.

Regards,
Markus
